[project]
name = "se-ai-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit==2.6.3",
    "ollama==0.5.1",
]

[dependency-groups]
dev = [
    "lefthook>=1.12.2",
    "ruff>=0.12.7",
    "ty>=0.0.1a16",
]
