[project]
user_env = []
session_timeout = 3600
user_session_timeout = 86400 # 1 days
cache = false
transports = ["websocket"]
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = true
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true
allow_thread_sharing = true

[features.spontaneous_file_upload]
enabled = true
accept = ["image/*", "application/pdf"]
max_files = 6
max_size_mb = 2

[features.audio]
sample_rate = 24000

[features.mcp.sse]
enabled = false

[features.mcp.stdio]
enabled = true
allowed_executables = ["npx", "uvx"]

[UI]
name = "Cogno"
default_theme = "dark"
default_sidebar_state = "open"
cot = "full"
custom_css = "/public/custom.css"
alert_style = "modern"
login_page_image = "/public/logo.jpg"
login_page_image_filter = "contrast-100 blur-none"
login_page_image_dark_filter = "contrast-100 blur-none"
logo_file_url = ""
default_avatar_file_url = ""

[meta]
generated_by = "2.6.3"
