name: Code Quality
permissions:
  contents: read
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv sync
      - run: uvx ruff check .
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv sync
      - run: uvx ruff format .
